title: Sehwan
description: > # this means to ignore newlines until "baseurl:"
  세환 블로그.
permalink: ':title/'
baseurl: "/" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Banner settings
video: mountains.mp4 # add banner video. Add your video file to the folder video

# Author settings
author-pic:  face.jpg# your photo
author-name: KIM-SEHWAN
about-author: Hello.
email: your-email@domain.com # your email
phone: (496)-169-6557 # your pnone number
website: https://dwayne.example.com # you website

# Social link
google_url:    # add url link
twitter_url:   # add url link
instagram_url: # add url link
pinterest_url: # add url link
dribbble_url:  # add url link
facebook_url:  # add url link

# Disqus
discus_identifier: kmk4204

# Newsletter
mailchimp: # add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e

# Tracker
analytics:

# Paginate
paginate: 12
paginate_path: /page:num/

# Build settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate-v2

include: [_pages]
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]

# code highlighter
highlighter: rouge

encoding: UTF-8

